### ISSUE TITLE
Add support for NATS messaging app

### ISSUE THREAD

**Issue by chmike** [agnivade/funnel#24]
In the list of supported targets, could you add support for NATS (https://nats.io/) ?
It's an alternate solution to Kafka written in go.

**Comment by agnivade** [comment]
Ah yes, I have heard about NATS. Sure, I can add support for that.

Are you looking to publish to NATS using funnel ?

**Comment by chmike** [comment]
If we use funnel for our project, that is what we would do. The idea of funnel is very attractive. I will definitely try it.

**Comment by agnivade** [comment]
@chmike - Its done ! Give it a spin and let me know how it goes :)
