### ISSUE TITLE
Add support for roll over by date

### ISSUE THREAD

**Issue by ShevaXu** [agnivade/funnel#27]
So far Iog to file can only be conditioned on max-lines or max-bytes, but sometimes daily rotation is more appreciated. 

In [logrotate](http://www.linuxcommand.org/man_pages/logrotate8.html) there are also options for `daily/weekly/monthly`.

So maybe consider adding daily roll over?

**Comment by agnivade** [comment]
I actually wanted to keep this tool with minimal features. Adding time based rotation is certainly possible but I will have to see about it. For now, if you can get an approx idea of how many lines your app is generating in a single day, maybe you can put that no. in the max_lines variable. I know its a hack, but its something.

Does this work for you ?

**Comment by dserodio** [comment]
@ShevaXu, did you implement this? I was looking for date-based file rolling too...

**Comment by ShevaXu** [comment]
No, I use logrotate as an external tool for file rolling. It works quite well.
